llm:
  provider: openai
  model: gpt-4o
  maxTokens: 8192
  maxSteps: 3
  maxRetries: 5
mcp:
  servers:
    - type: stdio
      command: deno
      args:
        - run
        - "-A"
        - jsr:@arcfra/neutree-mcp-servers/servers/hf2catalog
