apiVersion: v1
kind: ModelCatalog
metadata:
  name: deepseek-r1-distill-qwen-14b
  display_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  labels:
    icon_url: 'https://cdn-thumbnails.huggingface.co/social-thumbnails/deepseek-ai.png'
    hf_repo_url: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B'
spec:
  model:
    registry: ''
    name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
    file: model-00001-of-000004.safetensors
    version: ""
    task: text-generation
  engine:
    engine: vllm
    version: v0.8.5
  resources: {}
  replicas:
    num: 1
  deployment_options:
    scheduler:
      type: consistent_hash
      virtual_nodes: 150
      load_factor: 1.25
  variables:
    RAY_SCHEDULER_TYPE: consistent_hash
    engine_args:
      tensor_parallel_size: 1
      max_model_len: 32768
      enforce_eager: false
      gpu_memory_utilization: 0.95
      enable_chunked_prefill: true
      served_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
      tool_call_parser: hermes
      reasoning_parser: deepseek_r1
      enable_reasoning: true