apiVersion: v1
kind: ModelCatalog
metadata:
  name: nomic-embed-text-v1-gguf
  display_name: nomic-ai/nomic-embed-text-v1-GGUF
  labels:
    icon_url: 'https://cdn-thumbnails.huggingface.co/social-thumbnails/nomic-ai.png'
    hf_repo_url: 'https://huggingface.co/nomic-ai/nomic-embed-text-v1-GGUF'
spec:
  model:
    registry: ''
    name: nomic-ai/nomic-embed-text-v1-GGUF
    file: nomic-embed-text-v1.Q2_K.gguf
    version: ""
    task: text-embedding
  engine:
    engine: llama-cpp
    version: v0.3.7
  resources:
    cpu: "1"
    memory: "1"
  replicas:
    num: 1
  deployment_options:
    scheduler:
      type: pow2
  variables:
    RAY_SCHEDULER_TYPE: pow2
