apiVersion: v1
kind: ModelCatalog
metadata:
  name: qwen2-5-vl-3b-instruct
  display_name: Qwen/Qwen2.5-VL-3B-Instruct
  labels:
    icon_url: 'https://cdn-thumbnails.huggingface.co/social-thumbnails/Qwen.png'
    hf_repo_url: 'https://huggingface.co/Qwen/Qwen2.5-VL-3B-Instruct'
spec:
  model:
    registry: ''
    name: Qwen/Qwen2.5-VL-3B-Instruct
    file: model-00001-of-00002.safetensors
    version: latest
    task: text-generation
  engine:
    engine: vllm
    version: v0.8.5
  resources: {}
  replicas:
    num: 1
  deployment_options:
    scheduler:
      type: consistent_hash
      virtual_nodes: 150
      load_factor: 1.25
  variables:
    RAY_SCHEDULER_TYPE: consistent_hash
    engine_args:
      tensor_parallel_size: 1
      max_model_len: 32768
      enforce_eager: false
      gpu_memory_utilization: 0.95
      enable_chunked_prefill: true
      served_model_name: Qwen/Qwen2.5-VL-3B-Instruct
      tool_call_parser: hermes