apiVersion: v1
kind: ModelCatalog
metadata:
  name: qwq-32b-preview
  display_name: Qwen/QwQ-32B-Preview
  labels:
    icon_url: 'https://cdn-thumbnails.huggingface.co/social-thumbnails/Qwen.png'
    hf_repo_url: 'https://huggingface.co/Qwen/QwQ-32B-Preview'
spec:
  model:
    registry: ''
    name: Qwen/QwQ-32B-Preview
    file: model-00001-of-00017.safetensors
    version: latest
    task: text-generation
  engine:
    engine: vllm
    version: v1
  resources: {}
  replicas:
    num: 1
  deployment_options:
    scheduler:
      type: consistent_hash
      virtual_nodes: 150
      load_factor: 1.25
  variables:
    RAY_SCHEDULER_TYPE: consistent_hash
    engine_args:
      tensor_parallel_size: 1
      max_model_len: 32768
      enforce_eager: true
      gpu_memory_utilization: 0.95
      enable_chunked_prefill: true
      tool_call_parser: hermes
      served_model_name: Qwen/QwQ-32B-Preview
